wget https://raw.githubusercontent.com/arhitekture/AR19/master/sse.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/mmx.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/muv.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/sort.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/sort10.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/heming.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/tribr.asm
wget https://raw.githubusercontent.com/arhitekture/AR19/master/fib.asm
wget https://raw.githubusercontent.com/arhitektura/arh/master/rm.sh
